### PR TITLE
New: _canCycleThroughPagination functionality added (fixes #286)

### LINKED ISSUE #286: _canCycleThroughPagination conflict with narrative controls
### Subject of the issue/enhancement/features
I think this is a bug. Certainly not intuitive.

### Your environment
FW 5.33.1
The hotgraphic version I'm using is 6.7.0, but I've just created a brand new course and the same issue exists in hotgraphic version 6.8.0

### Steps to reproduce
In your hotgraphic component, set `"_canCycleThroughPagination": true;` and `"_isNarrativeOnMobile": true;`

### Expected behaviour
When the HG reverts to narrative on mobile, the right narrative control should either be disabled when the last item is reached, or it should be enabled and take you back to the first item (i.e. cycle).

### Actual behaviour
It's not doing either - it's enabled but doesn't do anything.

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#286 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### New
* _canCycleThroughPagination functionality added (fixes #286)

[//]: # (Mention any other dependencies)
Potentially put this release on hold until we can discuss/come up with a better way of indicating completion.

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Comment by kirsty-hames** [comment]
> Potentially put this release on hold until we can discuss/come up with a better way of indicating completion.

Hey @joe-allen-89, I've added some suggestions regarding the display of completion in https://github.com/adaptlearning/adapt-contrib-narrative/issues/288

**Comment by kirsty-hames** [comment]
Functionality wise, this works as expected testing in Chrome/Safari/FF on Mac and Safari iPhone.

When tabbing/testing with a screen reader, because the back button receives focus before the next button, the back button is read as _"Back to Narrative item 3 title (item 3 of 3)"_. I think this is confusing when you haven't visited the first item yet. From a UX perspective, I'd expect a Narrative to be a linear 1, 2, 3 etc. With this in mind, I think I'm inclined to agree with some of the [comments](https://github.com/adaptlearning/adapt-contrib-narrative/issues/286#issuecomment-1847079523) made in the original issue.

> Narrative is functionally differrent to the hotgraphic. The main reason cycling is requested for hotgraphic is because you can 'start' at any pin and clients find it too cumbersome to click in and out of pin/notify. Narrative doesn't have this issue as it always starts at the beginning.

**Comment by oliverfoster** [comment]
This issue is only to solve what happens with the `_canCycleThroughPagination` property when a narrative replaces a hotgraphic on mobile, where the hotgraphic has `_canCycleThroughPagination=true`.

Narrative does not have its own `_canCycleThroughPagination` property.
Narrative is always linear, it always starts from index 0 (akin to an ordered list).
Hotgraphic is not linear, the pins can be clicked in any order (akin to an unordered list).
When the narrative replaces the hotgraphic, the list that it represents does not inherit extra order that looping/cycling would break.

In the exploration of this issue we have identified that the narrative does not show completion #288.

Currently the narrative buttons are not disabled at the ends but they _also_ do not loop/cycle. The buttons are enabled but do nothing #286.
 
We have two possible choices to solve this issue:
1. Always disable the narrative buttons at the ends
2. Allow the narrative buttons to loop/cycle when the narrative replaces a hotgraphic on mobile where the hotgraphic has `_canCycleThroughPagination=true`

> When tabbing/testing with a screen reader, because the back button receives focus before the next button, the back button is read as "Back to Narrative item 3 title (item 3 of 3)". 

This is as expected with a looping carousel/narrative according to [wcag](https://www.w3.org/WAI/tutorials/carousels/functionality/#add-previous-and-next-buttons).

Are you in favour of always disabling the narrative buttons at the ends? @kirsty-hames 

I'd like to add `_canCycleThroughPagination` to the narrative, with your [completion fixes](https://github.com/adaptlearning/adapt-contrib-narrative/issues/288) and possibly re-add the ability to click the indicators as it is in the [wcag implementation](https://www.w3.org/WAI/tutorials/carousels/functionality/#add-navigation-buttons).

**Comment by kirsty-hames** [comment]
Thanks for capturing all the discussion points @oliverfoster.

> When tabbing/testing with a screen reader, because the back button receives focus before the next button, the back button is read as "Back to Narrative item 3 title (item 3 of 3)".
> 
> This is as expected with a looping carousel/narrative according to [wcag](https://www.w3.org/WAI/tutorials/carousels/functionality/#add-previous-and-next-buttons).
> 
>Are you in favour of always disabling the narrative buttons at the ends? @kirsty-hames

I personally find it odd and would be in favour of always disabling the narrative buttons at the ends. However, regardless of personal opinion, if wcag have set a standard users will be expecting this functionality if it exists elsewhere.

> I'd like to add _canCycleThroughPagination to the narrative, with your https://github.com/adaptlearning/adapt-contrib-narrative/issues/288 and possibly re-add the ability to click the indicators as it is in the [wcag implementation](https://www.w3.org/WAI/tutorials/carousels/functionality/#add-navigation-buttons).

Same goes for re-adding the ability to click the indicators. I personally find the wcag implementation cumbersome to navigate and read the info of each slide. That could be down to my SR keyboard skills though. I'm less keen on adding this but again happy to follow wcag for setting consistent functionality/UI. 

Where there can be a lot of difference in opinion when it comes to implementation and this is often questioned by clients. Following wcag does help with those conversations and we have a reference point for following best practice.

**Comment by oliverfoster** [comment]
> Following wcag does help with those conversations and we have a reference point for following best practice.

We can choose not to follow. 

I agree that the clickable indicators is an odd one. Having them clickable is handy and expected oftentimes for sighted users but terrible for screen reader users. If included it has to be included for both. 

The looping behaviour is usually for unordered carousels, having items that could appear in any order. Narrative can also and usually does a linear story with order, where the looping behaviour is a bit less meaningful. Without the completion indication, looping on a mandatory narrative would be a bit unfair, the user would have to remember that they'd seen the first slide or notice the backward slide.

I think the ordered/unordered list distinction is where the contention between wcag and Adapt comes from.

**Comment by joe-allen-89** [comment]
Moving this ticket back to needs reviewing as https://github.com/adaptlearning/adapt-contrib-narrative/pull/301 has been merged allowing us to show completion within the progress indicators.

**Comment by guywillis** [comment]
Functionally, the proposed works as you'd expect. 

However, I agree with Kirsty about the read order being confusing to non visual users. I think I would be in favour of always disabling start and end narrative buttons regardless of the Hotgraphic setting.

**Comment by joe-allen-89** [comment]
After discussion on the OS call most people agree with not including the cycling functionality to the narrative and instead disabling the back/next buttons on last/first items. Moving back to assigned for changes to be made.

**Comment by joe-allen-89** [comment]
Closing PR, as discussed the functionality is changing and a new PR will be raised.

**Pull request closed without merging**
