### PR TITLE
Hide next button when there is one slide only

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**
This hide the next button as well as the prev button when there is one slide only!!
Fixes issue https://github.com/adaptlearning/adapt-contrib-narrative/issues/151

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
This makes sense with the following lines:
https://github.com/adaptlearning/adapt-contrib-narrative/blob/master/js/adapt-contrib-narrative.js#L234-L237

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
