### PR TITLE
Added default text for strapline and changed default value for _setCompletionOn

### PR DESCRIPTION
**Pull request by bell87**

### CODE REVIEW

**Comment by chucklorenz** [comment]
maybe a more standard word used in place of 'Tap'? Perhaps 'Click' or 'Select'.

**Comment by moloko** [comment]
Yeah looking at it, `strapline` is more typically used as a title for the item rather than an instruction

**Comment by ryan-lynch** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Comment by bell87** [comment]
The same change was approved and merged in the hotgraphic component: https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/97e70d801ce95bade046174ff9e4ffb857c4ed57

**Comment by moloko** [comment]
@bell87 yeah I appreciate that but in retrospect it was an error - using `strapline` in this way results in a doubling up of instruction text:
2016-05-24 12_40_29-adapt version 2 0 demonstration _ presentation components

**Comment by moloko** [comment]
this is what it should look like:
shouldbe

**Comment by bell87** [comment]
Hi @moloko in the interest of consistency I've reverted the hotgraphic component strapline default value back to the way it was: https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/132

**Comment by moloko** [comment]
@bell87 - excellent, thanks. sorry for not spotting this in the original PR

**Comment by moloko** [comment]
@bell87 do you want to change this so that it's just 'default value for `_setCompletionOn`'? That sounds like a useful change.

**Comment by moloko** [comment]
anything more to be done on this or can I close?

**Comment by brian-learningpool** [comment]
This can be closed.

**Pull request closed without merging**
