### PR TITLE
Resolves #1596, adds support for swipe functionality on narrative

### PR DESCRIPTION
**Pull request by AaronmcL**

### CODE REVIEW

**Comment by brian-learningpool** [comment]
@AaronmcL, this actually might need to change if/when https://github.com/adaptlearning/adapt_framework/pull/1640 goes in.

**Comment by oliverfoster** [comment]
yea, probs just need to remove the 'libraries/jquery.mobile.custom' line

**Comment by simondate** [comment]
May I suggest:

* Hiding the buttons on touch devices
* Having a touch specific instructional text

**Comment by lc-thomasberger** [comment]
Thanks @AaronmcL 
Tested on iOS9 and Android and works like a charm.

The suggestions raised by @simondate make a lot of sense to me. Maybe add a option to hide buttons on touch instead of always hiding them on touch devices. When the buttons are hidden, we will need a different instruction Text.

`"_hideButtonOnTouch": true,`
`"touchInstruction": "This instruction text is rendered when the buttons are disabled",`

**Comment by moloko** [comment]
I agree with @lc-thomasberger - hiding buttons on touch should be an option not the default

**Comment by simondate** [comment]
Hiding buttons for `.touch` only could actually be quite problematic. Lots of Windows laptops have touch screens but that doesn't necessarily mean they will be using the touch screen all the time.

Maybe we could make some distinction based upon touch and screen size too?

**Comment by brian-learningpool** [comment]
Removing the buttons entirely makes it slightly less intuitive to me.  I've seen instances where users attempt to swipe from the arrows and the buttons are a visual indicator that the UI scrolls horizontally left, right, or in both directions.

Can we give the removal of the buttons and touch specific instruction text more thought and raise as a separate ticket?

**Comment by sarveshwar-gavhane** [comment]
can we reuse the code https://github.com/adaptlearning/adapt-contrib-narrative/blob/master/js/adapt-contrib-narrative.js#L298-L307 ?? instead of writing same code again

**Comment by moloko** [comment]
agree with @sarveshwar-gavhane - a certain amount of refactoring could be done here just having a think about how best to do it

**Comment by NayanKhedkar** [comment]
👍 @sarveshwar-gavhane

**Comment by moloko** [comment]
does anybody know what the intention of the code `stage = (stage + numberOfItems) % numberOfItems;` is? I mean I can kind of see the intention but in reality I don't think it's ever actually doing anything useful!

**Comment by NayanKhedkar** [comment]
you are right @moloko i think no longer required the code we can simply passed stage to setStage.

**Comment by moloko** [comment]
OK so maybe what we need to do is refactor so that we have `navigateForward` and `navigateBack` methods. The swipe events could be bound directly to the appropriate method; the `click .narrative-controls` should still call `onNavigationClicked` but could be greatly simplified to something like :
```js
if ($(event.currentTarget).hasClass('narrative-control-right')) {
    this.navigateForward();
} else {
    this.navigateBack();
}
```
I'm also wondering what the purpose of the `_active` model attribute is... anyone know?

All of this will of course need to be redone in #170

**Comment by brian-learningpool** [comment]
Been some time since I looked at this plugin but does `_active` relate to whether the item is rendering as a narrative or a hot graphic?

**Comment by moloko** [comment]
@brian-learningpool I had that thought too, the only two references to it are in `setupNarrative` (where it gets to set to `true` and `onNavigationClicked` where it will return early if not set. So it's not very clear why exactly it's needed.

**Comment by sarveshwar-gavhane** [comment]
@moloko either above approaches or we can simply add ``` || isSwipeLeft ``` in existing code

**Comment by moloko** [comment]
closing due to inactivity and being considerably out of date. still be nice to get this feature in though, just need to revisit properly

**Pull request closed without merging**
