### PR TITLE
Adds extra controls functionality

### LINKED ISSUE #101: Would be nice to change the position of the navigation arrows to the text area
Instead of just having the arrows on the image, it would be nice to position the arrows either above or below the text as a configuration. This is purely an look & feel for the desktop version. Functionality would remain the same

### PR DESCRIPTION
**Pull request by darylhedley**
Controls can now be placed in the text area
Fixes #101

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
Nice. +1

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
Really nice. Would be good to get the Travis build passing though.

**Comment by dancgray** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Pull request merged**
