### PR TITLE
Fix compatibility with framework 3

### PR DESCRIPTION
**Pull request by tomgreenfield**
Resolves https://github.com/adaptlearning/adapt_framework/issues/2348.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Should this be targeted at a `v3-fixes` branch though rather than `master`?

**Comment by tomgreenfield** [comment]
Needs to be `master` and released as v4.0.1 due to the way the CLI and authoring tool queries the latest compatibile version.

**Comment by brian-learningpool** [comment]
Couldn't we just re-tag 4.0 with the correct framework dependency?

**Comment by tomgreenfield** [comment]
Bit late in the day for that I'm afraid – it won't fix already broken installations.

**Comment by brian-learningpool** [comment]
I know broken installations can't be corrected without upgrading the plugin, but wouldn't it correct the plugin versioning going forward at least?  E.g.
```
3.0.3 - framework: >=3.2
4.0.1 - framework: >=4.0
```
Meanwhile 4.0.0 is re-tagged with `framework: >=4.0` in order to correct future CLI installations.

**Comment by tomgreenfield** [comment]
Superceded by #187 & #188.

**Pull request closed without merging**
