### PR TITLE
fixes ABU-1114

### LINKED ISSUE #146: A narrative with no items will break stop the page from loading
This is possibly an edge case, but if there are no items the narrative it will stop the page from rendering.

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**
Fixes #146

### CODE REVIEW

**Comment by moloko** [comment]
sorry @sarveshwar-gavhane this doesn't seem to fix the issue - which is that you get a JS error if `_items` is missing from the .json

The error is currently occurring on [L63](https://github.com/sarveshwar-gavhane/adapt-contrib-narrative/blob/ABU-1114/js/adapt-contrib-narrative.js#L63) (in your modified version).

**Comment by moloko** [comment]
+1 certainly prevents the JavaScript error for me now. it is maybe also worth adding a console.warn() to point out that there are no `_items`? @brian-learningpool as you logged the original ticket, what do you think?

**Comment by brian-learningpool** [comment]
@sarveshwar-gavhane, can you change the code to this?
`if (!this.model.has('_items') || !this.model.get('_items').length) return;`

Otherwise if the `_items` property is set, such as in the authoring tool, but it doesn't contain any items this throws another JavaScript error.  We should probably think about doing something with the template too, as some `<div>` controls are rendered.

**Comment by tomgreenfield** [comment]
I've found that `if (_.isEmpty(items)) return;` reads really nicely in these sorts of cases.

**Comment by sarveshwar-gavhane** [comment]
yeah sure @brian-learningpool

**Comment by belal-almassri-spongeuk** [comment]
Both @brian-learningpool solution and @tomgreenfield solution worked for me:


```if (!this.model.has('_items') || !this.model.get('_items').length) return; ```

**OR**

``` if (_.isEmpty(this.model.get('_items'))) return; ```

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
