### PR TITLE
RTL tabbing fixes ABU-1143

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by taylortom** [comment]
I'm getting an issue whereby I'm jumped to the top of the page when I get to the narrative via tabbing. It works fine when you then cycle through the components the second time.

Tested using the default course.

**Comment by sarveshwar-gavhane** [comment]
@taylortom I'm also getting same issue like you in LTR and RTL as well,so i removed narrative from component.json still i got the same issue,i think the problem is in graphic not in narrative,

**Comment by lc-thomasberger** [comment]
+1

**Pull request merged**
