### PR TITLE
ADAPT-7911-narrative-issues-with-images-on-IE11

### PR DESCRIPTION
**Pull request by eleanor-heath**
Linked issue: https://github.com/adaptlearning/adapt_framework/issues/3032

### CODE REVIEW

**Comment by oliverfoster** [comment]
Does it work with 3/5/7/6 & 9 items?

**Comment by eleanor-heath** [comment]
> Does it work with 3/6/7 & 9 items?

yes

**Comment by eleanor-heath** [comment]
> > Does it work with 3/6/7 & 9 items?
> 
> yes

I have tried 2, 3, 4, 5 and 6 items and its working

**Comment by eleanor-heath** [comment]
will try 7 and 9 items now to be sure

**Comment by oliverfoster** [comment]
Yea, don't worry about equally divisible numbers. Just the ones which produce the overhanging subpixel. 5 is always fine, my mistake. It's normally just the multiples of 3 but sometimes others.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by eleanor-heath** [comment]
Closing this PR as Ive another PR open that resolves this issue here https://github.com/adaptlearning/adapt-contrib-narrative/pull/209

**Pull request closed without merging**
