### PR TITLE
Update narrative.hbs

### PR DESCRIPTION
**Pull request by kunjsharma**
Added `title` existence check on `narrative-content-title` so can add content without title otherwise it add empty elements if no title given.

### CODE REVIEW

**Comment by moloko** [comment]
hi @kunjsharma thanks for this, would you mind ensuring that there's always a matching issue for each PR though? it might be worth having a quick read of our [guide to contributing code](https://github.com/adaptlearning/adapt_framework/wiki/Contributing-code#before-submitting)

**Comment by kunjsharma** [comment]
Thanks @moloko , much appreciated.

**Comment by moloko** [comment]
@kunjsharma did you mean to close this?

**Comment by kunjsharma** [comment]
Yes please...

**Pull request closed without merging**
